Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

# Style/StringLiteralsInInterpolation:
#   Enabled: false

# Style/StringLiterals:
#   Enabled: false

# Bundler/OrderedGems:
#   Enabled: false

Style/Documentation:
  Enabled: false
